### ISSUE TITLE
BLM skills broken

### ISSUE THREAD

**Issue by Matuno** [Grammernatzi/XIVComboPlugin#213]
```
06:11:27.558 | ERR | [XIVComboExpandedest] Don't crash the game
	System.NullReferenceException: Object reference not set to an instance of an object.
	   at XIVComboExpandedestPlugin.Combos.BlackDespairStarFeature.Invoke(UInt32 actionID, UInt32 lastComboMove, Single comboTime, Byte level) in /_/XIVComboExpanded/Combos/BLM.cs:line 266
	   at XIVComboExpandedestPlugin.Combos.CustomCombo.TryInvoke(UInt32 actionID, UInt32 lastComboActionID, Single comboTime, Byte level, UInt32& newActionID) in /_/XIVComboExpanded/CustomCombo.cs:line 143
	   at XIVComboExpandedestPlugin.IconReplacer.GetIconDetour(IntPtr actionManager, UInt32 actionID) in /_/XIVComboExpanded/IconReplacer.cs:line 157
06:11:27.558 | ERR | [XIVComboExpandedest] Don't crash the game
	System.NullReferenceException: Object reference not set to an instance of an object.
	   at XIVComboExpandedestPlugin.Combos.BlackScatheFeature.Invoke(UInt32 actionID, UInt32 lastComboMove, Single comboTime, Byte level) in /_/XIVComboExpanded/Combos/BLM.cs:line 479
	   at XIVComboExpandedestPlugin.Combos.CustomCombo.TryInvoke(UInt32 actionID, UInt32 lastComboActionID, Single comboTime, Byte level, UInt32& newActionID) in /_/XIVComboExpanded/CustomCombo.cs:line 143
	   at XIVComboExpandedestPlugin.IconReplacer.GetIconDetour(IntPtr actionManager, UInt32 actionID) in /_/XIVComboExpanded/IconReplacer.cs:line 157
06:11:27.558 | ERR | [XIVComboExpandedest] Don't crash the game
	System.NullReferenceException: Object reference not set to an instance of an object.
	   at XIVComboExpandedestPlugin.Combos.BlackFire2Feature.Invoke(UInt32 actionID, UInt32 lastComboMove, Single comboTime, Byte level) in /_/XIVComboExpanded/Combos/BLM.cs:line 344
	   at XIVComboExpandedestPlugin.Combos.CustomCombo.TryInvoke(UInt32 actionID, UInt32 lastComboActionID, Single comboTime, Byte level, UInt32& newActionID) in /_/XIVComboExpanded/CustomCombo.cs:line 143
	   at XIVComboExpandedestPlugin.IconReplacer.GetIconDetour(IntPtr actionManager, UInt32 actionID) in /_/XIVComboExpanded/IconReplacer.cs:line 157
06:11:27.559 | ERR | [XIVComboExpandedest] Don't crash the game
	System.NullReferenceException: Object reference not set to an instance of an object.
	   at XIVComboExpandedestPlugin.Combos.BlackUmbralSoulFeature.Invoke(UInt32 actionID, UInt32 lastComboMove, Single comboTime, Byte level) in /_/XIVComboExpanded/Combos/BLM.cs:line 121
	   at XIVComboExpandedestPlugin.Combos.CustomCombo.TryInvoke(UInt32 actionID, UInt32 lastComboActionID, Single comboTime, Byte level, UInt32& newActionID) in /_/XIVComboExpanded/CustomCombo.cs:line 143
	   at XIVComboExpandedestPlugin.IconReplacer.GetIconDetour(IntPtr actionManager, UInt32 actionID) in /_/XIVComboExpanded/IconReplacer.cs:line 157

```

This seems to be the case for all BLM options. Tested PLD, that's working.

**Comment by Matuno** [comment]
I didn't get the memo that we switched to stg overnight, my bad. Works with the latest staging branch.
